### ISSUE TITLE
validation error at /sign_up changes URL to /sign_ups which 404s if a user refreshes

### ISSUE THREAD

**Issue by InstanceOfMichael** [luckyframework/lucky#1003]
here is my repo but it's almost a fresh lucky install. https://github.com/InstanceOfMichael/8e10827d9fbd3fd8b849413c75616d8e

**Comment by jwoertink** [comment]
Yeah, I guess that makes sense since we do a `post "/sign_ups"`. That's caused from https://github.com/luckyframework/lucky_cli/blob/master/src/browser_authentication_app_skeleton/src/actions/sign_ups/create.cr#L4

This should just be changed to `post "/sign_up"`.  We had discussed [removing route](https://github.com/luckyframework/lucky/issues/789) anyway. Maybe this is a good argument for that.
