### ISSUE TITLE
Add params to lucky routes

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1070]
I'm not sure if we have access to this or not, but I was just thinking how cool it would be if you ran `lucky routes`, and there was another column that displayed which params you needed on that action. That might be kind of cool for a quick api documentation type deal. 

```text
╔══════╦════════════════════════════════╦════════════════════════════════════════╗
║ Verb | URI                            | Action               | Params          ║
╠──────┼────────────────────────────────┼──────────────────────┼─────────────────╣
║ POST | /v1/authenticate               | Authenticate::Create | token : String  ║
╠──────┼────────────────────────────────┼──────────────────────┼─────────────────╣
```

Though... now after making this example, I just realized on smaller (more standard) screens, this could become a mess real quick with multiple params 😞  But maybe some has an idea?

**Comment by paulcsmith** [comment]
@jwoertink Cool idea! So specifically query params right? Since the path shows which named params are in it?

Another thought I had was maybe not using a table. Or making the table optional (useful when grepping)

```
POST /v1/authenticate
  Action > Authenticate::Create
  Params > token : String, page : Int32?, etc.
  Route helper > Authenticate::Create.with(token: "String") # Example route 
```

But with some colors and a nicer arrow. I think this is actually a bit easier to scan since you don't need to read a whole row. Would love to hear opinions on it though

**Comment by jwoertink** [comment]
oooo I do actually kind of like that. But yeah, query params defined from `param` method.
