### ISSUE TITLE
Add `current_page?` helper method to pages and components

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1073]
This will be used by https://github.com/luckyframework/lucky/issues/969

Should work similarly to Rails https://apidock.com/rails/ActionView/Helpers/UrlHelper/current_page%3F

```crystal
current_page?(User::Index)
current_page?(Users::Show.with(user.id))
current_page?("/raw/string")
```

By default it should *not* care about query params but passing `check_query_params: true` will include the path and query params

cc @wout

**Comment by wout** [comment]
@paulcsmith Do you want include functionality for full uri's, including `scheme`, `host` and `port`? Or only for `path` or `path` + `query`?

**Comment by paulcsmith** [comment]
@wout Great question. I think host, scheme and port should be options. But I'd also be ok shipping those in a separate PR to get the basic use case of path done. Up to you though!

**Comment by wout** [comment]
Ok, I'll have a look at host and port as well. However, I need a pointer here since Crystal's `HTTP::Request` does not carry scheme information. Is it available somewhere in Lucky?

I was wondering if it is relevant these days. I can't think of all the use cases, but isn't it either http or https? And if so, since https is becoming the default these days, should we even test on scheme?

**Comment by paulcsmith** [comment]
@wout Great point. We can skip that I think. Everyone should be using ssl and Lucky makes it easy to force with the ForceSslHandler. Also scheme shouldn't change what page is shown as long as the rest of the host and path match 👍

**Comment by wout** [comment]
@paulcsmith That's done then. :)
