### ISSUE TITLE
Specify nested params in a route

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky#1105]
I have a form that I'd like to pre-fill some data on. For example, adding a User to a Group and automatically specifying their first/last name. This works if I visit the path: `/groups/1/users/new?user:first=Edward&user:last=Loveall`.

When specifying this as a route to go to, I'd love to be able to do something like:

```crystal
Groups::Users::New.path(group, { user: { first "Edward", url: "Loveall" } })
```

This would require something like this in the action:

```crystal
class Groups::Users::New < BrowserAction
  param user : NamedTuple(first: String, last: String)
  # or something like
  nested_param first : String
  nested_param last : String
end
```

This returns various compile errors.

Currently the only way I can figure out how to make this work is:

```crystal
Groups::Users::New.path(group) + "?user:first=Edward&user:last=Loveall"
```

I also realize there's an ongoing discussion about removing nested params, so maybe this just has to wait for that.

**Comment by paulcsmith** [comment]
@edwardloveall I think you could approach this differently by passing the data in to your operation instead of using the query params:

```crystal
class Groups::Users::New < BrowserAction
  param first_name : String
  param last_name : String

  your_route do
    operation = SaveGroup.new(first_name: first_name, last_name: last_name)
  end
end

# Then your route:
Groups::Users::New.with(group, first_name: "Edward", last_name: "Loveall")
```

I think this approach is more resilient as it has more compile time checks (if you rename a column, or the type is wrong, you'll know)

There may also be an alternative to passing it in the query params, but it depends on what the flow looks like. Can you describe how this works from the user perspective? Like what actions they hit and what the pages (roughly) have on them?

**Comment by edwardloveall** [comment]
That worked great! I think I was trying to do too many things at once and wasn't able to get it all talking together. Thanks!
