### ISSUE TITLE
Add support for arrays in paginator

### ISSUE THREAD

**Issue by confact** [luckyframework/lucky#1106]
I have arrays of data that i would like to paginate that is not coming from a database.

It would be nice, if it is not, to be able to use the paginate for normal arrays with any class (`T`)

my example would be this:
```crystal
  def paginate(
    items : Array(T),
    per_page : Int32 = paginator_per_page
  ) : Tuple(Paginator, Array(T)) forall T
    pages = Paginator.new \
      page: paginator_page,
      per_page: per_page,
      item_count: items.size,
      full_path: context.request.resource

    updated_query = items[pages.offset...pages.offset+pages.per_page]
    {pages, updated_query}
  end
```

**Comment by paulcsmith** [comment]
Yes this would be great to have! I think I'd prefer to have a different method rather than overloading the existing method. Something like `paginate_array`, but yes it would work pretty much exactly like you described. 

LMK if you'd like to do a PR for this. Otherwise I'll see if I can tackle this for next release
