### ISSUE TITLE
Support `Nil` in memoize

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#1119]
https://github.com/luckyframework/lucky_cli/pull/508

It is sometimes useful to memoize things that can be nil. I think we can support this and it'd be great to have. We still shouldn't accept any other union, at least for now. But Nil union is pretty common and can definitely work

**Comment by jwoertink** [comment]
This is good because I actually just ran in to this. I have a query I have to make to check some settings and see if the setting exists then do one thing or not. So this could either return a string or nil. Without it memoizing, then it always runs that query. 

On a side note, I dig the way react `useMemo` works. It even allows for arguments to be passed in, so it will always cache that return value until a new argument is passed in. I'm not sure how they do it internally, but that would be great if we could figure out how to do that.

```crystal
memoize def get_user(id) : User
end

get_user(1) #=> store cache
get_user(1) #=> fetch cache
get_user(2) #=> store cache because a new key
get_user(1) #=> store cache again because it was wiped out from the previous
```

Maybe this works by creating a hash with some key and whatever the value is. Then the second call will just return that value even if that value is nil. The only way it makes the call again is if the key doesn't exist. We already have the escape hatch in the current implementation that lets you fetch the raw value, so we just keep that as well.. And, if we need sort of way to clear that, we could have a `Lucky.reset_memoize("get_user")` or something. This could just tell that memoize cache to dump whatever it has.
