### ISSUE TITLE
Unable to parse JSON data from request

### ISSUE THREAD

**Issue by brunto** [luckyframework/lucky#1148]
Crystal: 0.34.0
Lucky: 0.21.0

When I send some JSON data:
```
curl --location --request PUT 'http://localhost:5000/api/XXX/XXXX' \
--header 'Authorization: Bearer XXXXXXXXXXXXX' \
--header 'Content-Type: application/json' \
--data-raw '{ "roles": { "test": 123 } }'
```

My action looks like:
```
roles = params.get("roles")
Log.info{ roles }
Log.info{ roles.to_json }
test = {"test" => 123}
Log.info{ test.to_json }
```

The result of the code above is:

```
web |  ▸ {"test" => 123}
web |  ▸ "{\"test\" => 123}"
web |  ▸ {"test":123}
```

I think `Log.info{ roles.to_json }` must display `{"test":123}`

**Comment by matthewmcgarvey** [comment]
@brunto The discrepancy with the `roles.to_json` output is because you are calling `params.get("roles")`. `#get` does not attempt to parse the value of the key which means it remains a string. Switching to `params.nested("roles")` works the way you expect or [the docs](https://luckyframework.org/guides/http-and-routing/routing-and-params#params-from-json) explain that you can also use `params.from_json["roles"]`

**Comment by brunto** [comment]
@matthewmcgarvey thanks for this information, I already use from_json. 👍
