### ISSUE TITLE
Revisiting shipping docker-compose setups with Lucky

### ISSUE THREAD

**Issue by sevensidedmarble** [luckyframework/lucky#1155]
It's been a little while since the discussion in https://github.com/luckyframework/lucky/issues/671 and I thought it might be worth bringing up again -- there's important points raised in #671 but I think it's also extremely important to point out a good docker-compose setup out of the box removes the need for the user to run postgres in development, which is a huge gain. Heroku even has ways of deploying docker images nowadays.

It would be great if:
- The docker image in the root repository could be included in a build step in this repo to automatically push new images to an official lucky docker image on docker hub.
- A docker-compose setup was distributed along with the procfile to allow users who prefer a docker based workflow to get off the ground in one command.

The point was raised in #671 that maintaining the docker-compose file in the repo would be difficult, but I think with how popular this workflow is getting you'd have no shortage of people willing to volunteer their time keeping this particular workflow going. Amber does come with a docker-compose file out of the box after all as well.

**Comment by paulcsmith** [comment]
@Sevensidedmarble Thanks for opening this issue! We're still pretty spread thin, and even if people contribute we need to make sure the file we ship works. Since no one on the team uses Docker for local dev we won't really have real world apps to test with.

I do agree we need to make this easier though. Here is my thought on how we could approach this:

* Someone that uses Docker can maintain a Docker image and re-release when Lucky is released. 
  * They can control and maintain which will ease the burden on the core team and people using Docker can make tweaks and understand PRs that people make. If people make a PR to our docker compose I will not know how to review it :(
* Add guide on how to use Docker locally
  * Link to the Docker container on Docker hub and to the github repo

I think this strikes a great balance. Someone familiar with Docker can maintain the docker image and docker compose examples in the website. And it is findable since it'll be on the Lucky website.

If you'd like to start this effort or find someone who can that'd be wonderful! I also would like https://railsbytes.com in the future where people can easily plugin in different templates. I'd imagine a "Lucky Docker" template would be super helpful! But this needs a lot more work to do so not really on the radar for being relased anytime soon 🤪

**Comment by Sevensidedmarble** [comment]
I would love to contribute. GitHub has automatic actions for building images now. If someone with authority could make a Lucky account and repository on https://hub.docker.com/ we could then put a Dockerfile at the base of the repo (Amber's is a good one to look for for starting points) and then a GitHub action could build and deploy it to dockerhub when ever there's a push to a particular branch.

**Comment by josefrichter** [comment]
Hey folks, any progress here, please? I'd like to try Lucky, but ideally easy dockerized setup.

**Comment by jwoertink** [comment]
@josefrichter Hey Welcome to Lucky!

There's a few community members that are using Docker, and I saw [Stephen had responded to you in the gitter chat](https://gitter.im/luckyframework/Lobby?at=5ef60483d65a3b0292affff7) on setting that up. Maybe you can give that a shot and see if that works for you?

Unfortunately, getting Docker in to all Lucky apps by default may not happen for some time. The main issue is that none of the core team are really all that comfortable using it, and though several community members have offered up adding it in, we have yet to see anyone make that progress. 

What we'd like to see is someone in the community create their own repo along with detailed instructions on how to get all dockerized. Then push the community to using that. Next we would add guides on the Lucky website pointing to that repo. We could eventually move that in to the Lucky org down the road once it's all stable and fully optimized. But feel free to ask questions, and hop in to the gitter chat if you need any help! Glad to have you 😄

**Comment by Sevensidedmarble** [comment]
One first step that needs to happen is someone needs to make a Lucky repo up on dockerhub. I was hoping the core team could reserve the name, but maybe someone from the community should just do it first and then it can be transfered.

**Comment by jwoertink** [comment]
Yeah for sure. I think if someone in the community would like to take that step first, that'd be great.

**Comment by josefrichter** [comment]
Thank you. My Docker knowledge is rather passive, generally just consuming existing images. I personally don't have enough experience to knit everything together, especially in an ecosystem that I've never seen before, unfortunately.

**Comment by KCErb** [comment]
Hey folks, just found this thread today. I have such a repo which uses github actions to push up an image when crystal / lucky update: https://github.com/KCErb/lucky-crystal.

I'm right now spinning up a project that will use some `api-only` and `full`(i.e. yarn, webpack, browsersync) microservices all in Docker + Lucky. So I'm thinking about creating a github org, dockerhub account etc. with a name like 'lucky docker' or 'docker lucky' or something to that effect.

Then I'll move my LHD stuff as a sub project and contribute my new non-Hasura stuff as well. (Still love Hasura, but new project doesn't need GraphQL yet and it can always be added in later).

If you'd like to see more traction before giving me creds to have a more official place to put the images / repos that's fine. I'll update in this issue. Otherwise, let me know and I'd be happy to take this on.

**Comment by paulcsmith** [comment]
@KCErb This sounds great. I think doing your own dockerhub account is a great idea. When you are ready and everything is set up, feel free to open an issue on the website repo so we can try to fit it in one of the guides too!

**Comment by KCErb** [comment]
10-4 thanks @paulcsmith 

Also thanks for commenting. I don't get a notification for the reaction emojis and since I hadn't heard anything on this issue I guess I assumed there was little interest. Nice to see it might be useful to someone besides myself, so that'll motivate me to put in some time 👍

**Comment by paulcsmith** [comment]
Right on! Looking forward to seeing what you come up with :D

**Comment by KCErb** [comment]
Update :tada:

So I created an org that now has two repos:

https://github.com/luckyframework-docker/

My goal, for now, is just to curate some nice examples and keep a docker image up to date with crystal and lucky releases.

**Comment by matthewmcgarvey** [comment]
I'm happy that there are references for using docker with lucky! I don't think we're going to start shipping docker with generated apps for now
