### ISSUE TITLE
Create a Lucky.root method to allow intuitive access to project folder

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/lucky#1198]
It **looks** like `Dir.current` in a Lucky app will always return the root folder of the project, but I'm not confident that that's always true or sure about why.

What I'm after is something similar to `Rails.root` here:
https://github.com/rails/rails/blob/master/railties/lib/rails.rb#L63

It looks like we currently use `Dir.current` within the framework for the project path already:
https://github.com/luckyframework/lucky/blob/master/src/lucky/base_component.cr#L9

My naive suggestion would be to add this:
```cr
module Lucky
  def self.root
    Dir.current
  end
end
```

I'm new to Crystal from Ruby and would greatly appreciate input from someone with more experience to guide me through a pull request if it's agreed that this would be nice to have!

**Comment by wout** [comment]
I've been in that place too. :)

I think `Dir.current` is always right because the project is compiled to a single binary. Unlike with Rails where there are hundreds, sometimes thousands of files.

**Comment by jwoertink** [comment]
I think this is fine. A lot of people have asked what our equivalent was (including me), and this gives us the principle of least surprise.

**Comment by stephendolan** [comment]
@jwoertink where would this go, file-structure-wise?

I'd love to open a PR and contribute to help out the project.

**Comment by jwoertink** [comment]
Maybe just the root of the project? https://github.com/luckyframework/lucky/blob/master/src/lucky.cr

**Comment by paulcsmith** [comment]
I like the general idea, but I'm a bit nervous about making aliases because it introduces other problems. For example if someone comes from another Crystal framework or has general Crystal framework, they may wonder what is different about `Lucky.root` and `Dir.current`. In this case they are the same. So then people may wonder when to use one over the other, in which case it's whichever one you feel like.

It also can create fragmentation since some people might use Dir.current and others Lucky.root.

My suggestion would be to add `Lucky.root` but have it raise a compile time error saying to use `Dir.current`. That way when people try it they'll get a nice message saying what to use instead. This avoids fragmentation, is portable knowledge (you can use Dir.current in any Crystal program). We can even document it so it shows up in API docs, but says "Use Dir.current"

@stephendolan I agree with @jwoertink it'd probably go in the root 👍

**Comment by stephendolan** [comment]
Cool, assuming that my "real" job doesn't impose on my weekends as it has for the last few weeks, I'll throw up a PR soon!

**Comment by paulcsmith** [comment]
Awesome! Thanks @stephendolan

**Comment by stephendolan** [comment]
@paulcsmith / @jwoertink 

Is it really this simple, or am I missing something? Just want to make sure I'm on the right track before figuring out how to build a version of Lucky to use in an app and write the accompanying specs.

```cr
module Lucky
  Log              = ::Log.for("lucky")
  ContinuedPipeLog = Log.for("continued_pipe_log")

  # Use `Dir.current` to locate the root folder of your Lucky application.
  def root
    raise "Please use 'Dir.current' to locate the root folder of your Lucky application."
  end
end
```

**Comment by paulcsmith** [comment]
Pretty much! Though I would do a macro raise so it raises at compile time:

```crystal
{% raise "Please use Crystal's 'Dir.current' to return the root folder of your Lucky application." %}
```
