### ISSUE TITLE
`#redirect_back` should disallow external URLs

### ISSUE THREAD

**Issue by akadusei** [luckyframework/lucky#1199]
https://github.com/luckyframework/lucky/blob/6a8132dc999945440a17850d55731cffb83308a3/src/lucky/redirectable.cr#L71

The current implementation of `#redirect_back` relies on the HTTP Referer header, thus allows redirecting back to an external URL. This is probably undesirable, and *may* have security implications.

The referer header is easily spoofed, and the application *may* leak sensitive information to a third party.

I propose **one** of the following:

### 1. Add a `allow_external` parameter, set to `false` by default:

```crystal
# Following code is untested

def redirect_back(*, fallback : String, status : Int32 = 302, allow_external : Bool = false)
  unless referer = request.headers["Referer"]?
    return redirect to: fallback, status: status
  end

  # There's probably a better approach?
  URI.parse(referer).host.try do |host|
    referer = fallback unless Lucky::RouteHelper.settings.base_uri.includes?(host)
  end unless allow_external

  redirect to: referer, status: status
end
```

This will redirect to the fallback if referer header is not set, or if referer is an external URL:

```crystal
redirect_back fallback: Home::Index
```

This will redirect to the fallback *only* if the referer header is not set. It allows redirecting to an  external URL:

```crystal
redirect_back fallback: Home::Index, allow_external: true
```

### 2. Use sessions instead of a client-supplied referer

This may be achieved by having a `after` pipe that sets the previous page for every action:

```crystal
# Following code is untested

after :set_previous_page

def set_previouse_page
  session.set(:previous_page, request.resource)
  continue
end

# This retrieves, from session, the previous page set by the preceeding action (hopefully)
def previous_page
  session.get?(:previous_page)
end
```
```crystal
# Redirect back
def redirect_back(*, fallback : String, status : Int32 = 302)
  redirect to: (previous_page || fallback), status: status
end
```
If we go this route, external URLs are never used.

### 3. A combination of both techniques above

The application may prefer previous page from session, then fall back to referer header if not set.

This may be preferred, since a developer may decide to `skip :set_previous_page`

**Comment by jwoertink** [comment]
Ref: https://github.com/luckyframework/lucky/pull/1168

Thanks for bringing this up. I had the same mental gymnastics originally on what would be the best way to handle that. We ended up just rolling with an easy implementation for now, but we should definitely lock this up before 1.0. 

cc. @matthewmcgarvey

**Comment by matthewmcgarvey** [comment]
I did not implement this functionality because I did not understand the importance. The current implementation of `redirect_back` was taken from Rails so it should be easy enough to implement the rest of it https://github.com/rails/rails/blob/97c3a5605bacd62e5a01872dfe5e5976cd982115/actionpack/lib/action_controller/metal/redirecting.rb#L90

**Comment by paulcsmith** [comment]
Thank you so much for the thorough documentation and options. I actually think the session based approach is great. I've had issues with Rails redirect_back where the referer was a URL from a failed POST request and if you reload the page there is no corresponding GET request so it 404s.

What we could do with session is only set it if the request is a GET request. This should resolve the potential security issue and make the redirect back more reliable since it will only set it for GET requests and not POST/PUT.

What do you all think?

**Comment by akadusei** [comment]
I see this was partly discussed in #1168 

> The current implementation of `redirect_back` was taken from Rails...

That should make it easy, then. I would rather `allow_other_host` (or whatever we decide to call it) defaults to `false`.

> I actually think the session based approach is great.

Me too.

> What we could do with session is only set it if the request is a GET request.

Good catch!
