### ISSUE TITLE
Decrease learning curve

### ISSUE THREAD

**Issue by pannous** [luckyframework/lucky#1207]
Following the new user guide at

https://luckyframework.org/guides/http-and-routing/routing-and-params

The server throws these errors:

```
Error: undefined constant Auth::AllowGuests

Error: undefined constant BrowserAction
```

**Comment by jwoertink** [comment]
Hey @pannous, Welcome to Lucky!

Can you share a bit more information on how you generated your app? Did you go through the docs from the "Getting Started" page, or were you just looking to do something like a redirect, and ran in to this error after copying the code? 

It'll help to understand how you got to the error so we can come up with a better wording for future cases. Thanks!

**Comment by pannous** [comment]
modifying 'hello world' api app

http://127.0.0.1:5000/   "Hello Worldy from Home::Index"   works great

Just adding the line 'include Auth::AllowGuests' in class Home::Index < ApiAction

then tried `lucky gen.action.browser Users::Index`

http://127.0.0.1:5000/users/index/ gives 

```
9:36:20 PM web.1          |  In src/actions/users/index.cr:1:22
9:36:20 PM web.1          |   1 | class Users::Index < BrowserAction
9:36:20 PM web.1          |                            ^
9:36:20 PM web.1          |  Error: undefined constant BrowserAction
```

PS: 

```
  get "/test/" do
    plain_text "OK"
  end
``` 

doesn't work either

**Comment by jwoertink** [comment]
Ah. Ok, so the `BrowserAction` only exists for non API apps. When you run `lucky init` you're given 2 options `full` or `api`. https://luckyframework.org/guides/getting-started/starting-project#create-a-new-project. The API actions inherit from `ApiAction`, and the actions that will render web pages inherit from `BrowserAction`. 

Next, during the `lucky init` wizard, it asks you if you want to generate Auth for your app. By saying "yes", you'll be given the `Auth::AllowGuests` module. If you say "no", then `Auth` isn't added in.

As for your last issue there, are you saying when you make a request to `/test` in your app, you don't see "OK"? Since you generated an API app, you could do a cURL request to test this:

```
curl -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:5000/test
```

I can see where you get confused though. It sounds like we should make a tutorial for beginners to better explain some of the concepts. Maybe a section that says "Is this your first time with Lucky? Try this run through.." or something. I appreciate the feedback! This is helpful for us to understand how to make this easier to use for beginners!

**Comment by pannous** [comment]
ok the first two make sense

It compiles if one substitutes BrowserAction for ApiAction or uses `lucky gen.action.api Users::Index` with 'api'

However the curl results are still ... confusing:
```
 ~/apps/lucky/ curl -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:5000/users/index/
{"message":"Not found","param":null,"details":null}%                                                                                                                        ~/apps/lucky/ curl -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:5000/test        
{"hello":"Hello Worldy from Home::Index"}%                                                                                                                                  ~/apps/lucky/ curl -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:5000/how 
{"message":"Not found","param":null,"details":null}%      
```

**Comment by jwoertink** [comment]
Does your `Home::Index` action look like this? 

```crystal
# src/actions/home/index.cr
class Home::Index < ApiAction
  get "/test" do
    json({test: "Hello TEST"})
  end
end
```

**Comment by pannous** [comment]
Oh, now I get it: only the LAST route in Home::Index is effective.

```
class Home::Index < ApiAction
  include Api::Auth::SkipRequireAuthToken
  # include Auth::AllowGuests

  get "/test" do
    json({test: "Hello TEST"})
  end

  get "/bug" do
    json({bug: "Hello BUG"})
  end
end
```

`http://localhost:5000/users/index/` works without `http://localhost:5000/users/`

Chaos monkey mode closed ;)

**Comment by pannous** [comment]
Postmortem: 

Adding a line "The following examples are for the browser with auth configuration" to 

https://luckyframework.org/guides/http-and-routing/routing-and-params

would be helpful ;)

**Comment by jwoertink** [comment]
haha. Glad you got it solved. We do want to eventually make that throw an error. 

I like your suggestion. I'll make an issue on the site to add that in.

**Comment by paulcsmith** [comment]
Ah yes, we should also make it clear you should only add one route per action, and we should probably raise a compile-time error if you try to add multiple 👍 

Thanks for opening this and sharing your experiences. Making this easier for new people is definitely a big goal of ours!
