### ISSUE TITLE
Add mount alias

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#1215]
Related: https://github.com/luckyframework/lucky/issues/1049#issuecomment-653875308

We can add the `mount` keyword back in, but make it an alias to `m`. So in this case, it would work the same way as `m` does now. Then you could use either `m` or `mount`.

```crystal
mount Component, args: 1
```

The downside to this would be having an older larger codebase that has a mix of `m` and `mount` all throughout it, but the upside is that seeing `mount` is a little more clear on what is happening.

**Comment by paulcsmith** [comment]
I think we should avoid aliases since like you said it could lead to using both all over the place. It also means new people may be confused about which one to use and in reality both work exactly the same. 

I think instead we should change it back to `mount`. It's not much more typing and the `m` is hard to google anyway. What do you think?

**Comment by jwoertink** [comment]
Change it to `mount`, but leave it with the same signature? (i.e. my example above)

**Comment by paulcsmith** [comment]
Yeah, same signature since that will be require for the other goodies coming down the line (automatically passing stuff like `context`, `current_user`, etc.)

**Comment by jwoertink** [comment]
Cool. I'm ok with that. Might as well get all our breaking changes in now! 😂

**Comment by paulcsmith** [comment]
Yeah haha. And luckily a rename is easier to revert than a method signature change. We can provide some simple find and replace commands for people to use

* `m ` -> `mount `
* m(` -> `mount(`

And that should do the trick!
