### ISSUE TITLE
Flash messages are always displayed for 2 requests

### ISSUE THREAD

**Issue by odinhb** [luckyframework/lucky#1271]
I'm having trouble with the flash messages.

I'm doing something similar to the generated browser sign_in endpoint:
```crystal
get "/some_endpoint" do
  flash.info = "here is a message"
  html SomePage
end
```
It doesn't matter if I use `flash.keep` or not. The flash message shows up in the response (as it should), but it doesn't go away if I refresh or trigger another request.

I would expect it to disappear in the response to the second request.

Lucky version: 0.24.0

I noticed that in `Shared::FlashMessages` we loop over flash keys using `#each`, but in the implementation of `Lucky::FlashStore` `#each` is delegated to `#all`, which means we are looping over both the `@next` messages and the `@now` messages.

I also noticed that in `Lucky::FlashStore#set` we modify `@next` instead of `@now`, meaning there is no difference between calling `flash.keep` or not, as `@next` gets put in a cookie (i assume thats why `#to_json` is there), sent back by the client and put back in `@now` for the next response, essentially always being "kept" and thus being displayed in both responses.

I appended a monkey-patch in `src/app.cr` which looks like this:
```crystal
class Lucky::FlashStore
  def set(key : Key, value : String) : String
    @now[key.to_s] = value
  end
end
```
And it seems to work fine now, but this is not the correct implementation, is it? I'm finding the implications of the implementation a bit hard to hold in my head.

**Comment by jwoertink** [comment]
Thanks for reporting! Flash has seemed to be pretty tricky. The last major change was https://github.com/luckyframework/lucky/pull/1169 which may have caused some issues. I'll try to dig in soon and see if I can figure out what's up.

**Comment by matthewmcgarvey** [comment]
After reading through Rails' flash implementation, specifically [here](https://github.com/rails/rails/blob/f2bd5197ee55e047f7cc86889b351d262a106e08/actionpack/lib/action_dispatch/middleware/flash.rb#L6-L7), it's becoming clear that we implemented flashes incorrectly.

The idea in rails is that normal flashes set in an action are shown in the _next_ action that handles a request for the user. The idea would be that the create endpoint sets a flash and redirects to the show which actually processes the flash and renders html. If you want to show a flash message in the _current_ action you call `flash.now` https://github.com/rails/rails/blob/f2bd5197ee55e047f7cc86889b351d262a106e08/actionpack/lib/action_dispatch/middleware/flash.rb#L229-L231

Where we went off the "rails", I believe, is combining `now` and `next` with this `all` method https://github.com/luckyframework/lucky/blob/3e0fdd29f034db190e94b23a02ef0f2ed5146f39/src/lucky/cookies/flash_store.cr#L29-L31
Now when you go to render flash messages and call `flash.each`, it gives you `now` and `next` instead of just `now`.

The other thing that I think is happening is that users are being too liberal with calling `flash.keep` when they shouldn't/don't need to. The main place this should be used for is when redirecting a request that would have specified flashes to handle so that the redirected to location handles them.

**Comment by matthewmcgarvey** [comment]
Article on Rails' flash messages https://www.rubyguides.com/2019/11/rails-flash-messages/

**Comment by stephendolan** [comment]
Agreed, @matthewmcgarvey. I'm guilty of calilng `flash.keep` too often as well, and while I never really got confused using them in Rails, I've found Lucky's flash messages to be a bit difficult to reason about.

**Comment by matthewmcgarvey** [comment]
Besides rails, here's some other flash implementations I looked into. All of them set a value that is accessible during the current request and the next. The only difference I saw was that some remove flash messages when they're accessed so that they aren't passed on to the next request.

- Laravel https://laravel.com/docs/8.x/session#flash-data
- Phoenix https://hexdocs.pm/phoenix/controllers.html#flash-messages
- Express middleware https://github.com/jaredhanson/connect-flash
  - removes the message from flash after accessing
- Django middleware https://docs.djangoproject.com/en/3.1/ref/contrib/messages/
  - seems to remove "used" messages from being passed to the next request

**Comment by jwoertink** [comment]
Just dropping in here. Two things I want in my flash messages without having to think about which methods to call are

* If a flash message is set, and multiple redirects happen, but the flash was never rendered, then carry it all the way through until it is rendered
* Once the flash is rendered, don't show me again. 

This was always tricky for me in rails, I'd either have a deal where I logged in, saw my "welcome" flash, clicked to a dashboard and still saw the message. Or I'd have a deal where i logged in, but was trying to go to a page I didn't have access to which would do a secondary redirect to another page, and the flash would never show.

I'd like if I didn't have to think about any secondary interfaces like calling `.now` or `.keep` or whatever. I'm sure we can come up with a nice system for this!

**Comment by matthewmcgarvey** [comment]
https://github.com/luckyframework/lucky/pull/1370 should help with the scenario where someone wants to set a flash message in an action that renders HTML. The other problem that I don't really know of a way to fix is people calling `flash.keep` when they shouldn't. One of the things I noticed while working in this area of the code base is that we actually call `flash.keep` whenever we return a redirect. https://github.com/luckyframework/lucky/blob/0b9be66ab1e0c238aa8715cdb3b195ceae59459b/src/lucky/redirectable.cr#L124

Thinking about it, since we do that, I can't think of a scenario where users should ever call `flash.keep` in their application unless they specifically want the flash message to render more than once.

**Comment by matthewmcgarvey** [comment]
@jwoertink While express and django seem to drop flash messages when they are used, neither of them are part of the "core" codebase. I don't think I can trust them like I do Rails and Laravel and neither of them do this. Until someone has a brilliant idea, I think emulating Rails/Laravel is the best choice, even if it's a bit confusing.
