### ISSUE TITLE
Text for HTTP error 418 is ungrammatical

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#1306]
Error 418 returns an ungrammatical error text.
```
POST /api/image
 ▸ Handled by Image::Create
 ▸ Failed to save SaveImage. Validation errors size is too short
 ▸ Sent 418 Im a teapot (7.63ms)
```

The 418 error code is used in examples on the website. Cute. But we should render the error correctly if we do that. Section 2.3.2 of RFC 2324 clearly renders "I'm a teapot" with the apostrophe.

Obvious, any language named "Crystal" should facilitate extension of the  Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0) to more powerful substances. Correction of the underlying implementation is essential for this work.

**Comment by BrucePerens** [comment]
Hm. Is this in the underlying HTTP package? Maybe I should file this on Crystal.

**Comment by jwoertink** [comment]
Yeah, this comes from crystal directly https://github.com/crystal-lang/crystal/blob/master/src/http/status.cr#L49 Weird thing though is that it has the apostrophe https://github.com/crystal-lang/crystal/blob/master/src/http/status.cr#L211 Maybe we are just calling `to_s` on the enum key instead of grabbing the description?

**Comment by jwoertink** [comment]
Yup, https://github.com/luckyframework/lucky/blob/master/src/lucky/logger_helpers.cr#L3 Just needs to be fixed here to grab the description.
