### ISSUE TITLE
Ability to render status codes on an html response

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky#1312]
**Describe the bug**
In a LuckyAction, I can do `plain_text 'ohai', status: 419` but I can't do `html Page, things, status: 419`

**Expected behavior**
The ideal DSL here isn't clear, and I don't know what a sane implementation would be. Here are some ideas:

```crystal
# could get lost among assignments
html Page, user: current_user, status: 419

# separate statement is verbose
status 419
html Page, user: current_user
```

**Comment by matthewmcgarvey** [comment]
One of the more extreme ideas would be to separate the rendering of html pages from the response.

```crystal
body = render Page, user: current_user
html body, status: 419
```

The only reason I'm thinking about it is so that all the response apis are the same. Without looking at the code, I believe that `html` is the only one that works differently

**Comment by jwoertink** [comment]
Yeah, the reason `html` is different is because `html` requires a Page object and is checked at compile-time vs the others that just say "pass in a string".

My guess is the tricky part here would be telling the macro how to differentiate between `status` being an arg to `TextResponse` and not to `SomePage`.
