### ISSUE TITLE
Laravel-Mix specific pathname ./public/mix-manifest.json is hardcoded in asset helpers.

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#1382]
At <https://github.com/luckyframework/lucky/blob/master/src/run_macros/generate_asset_helpers.cr#L5>
the pathname for the Laravel-Mix specific manifest name `./public/mix-manifest.json` is hardcoded. This is called `parcel-manifest.json` when using Parcel, etc.

**Comment by stephendolan** [comment]
A nice solve for this might be to add a (defaulted?) argument to `load_manifest`, then just forward that through to the macro Bruce mentioned:
https://github.com/luckyframework/lucky/blob/master/src/lucky/asset_helpers.cr#L11

**Comment by matthewmcgarvey** [comment]
The laravel mix integration should probably be pulled out of Lucky into a shard

**Comment by n-rodriguez** [comment]
> The laravel mix integration should probably be pulled out of Lucky into a shard

I agree. What if I want to use vanilla webpack?

**Comment by jwoertink** [comment]
I don't think we should pull it out in to a shard. This is part of our "Batteries included" part of Lucky. Removing it would end up causing other issues due to how we handle the asset checker system at compile-time. However, I do think we should make this file more configurable. 

Right now it's possible to use other build systems. I have a Lucky app using some plain webpack, and another using Gulp. 

```javascript
const manifestConfig = {
  merge: true,
  path: 'public/mix-manifest.json',
  base: 'public/'
}

gulp
  .pipe(rev.manifest(manifestConfig.path, manifestConfig))
  .pipe(revdel())
  .pipe(gulp.dest(manifestConfig.base))
```

We should add some guides on how to set up a few alternatives like parcel, gulp, and plain webpack similar to how we should a few different ways of deploying.
