### ISSUE TITLE
Comparison to H2O on the Techempower benchmarks

### ISSUE THREAD

**Issue by sevensidedmarble** [luckyframework/lucky#1413]
Apologies if this has an explanation or has already been discussed but when you go to the techempower benchmarks 'framework overhead' section, and filter only by crystal frameworks, for some reason Lucky is listed as being 'compared to' H2O, whilst all the other crystal frameworks are compared to just 'Crystal'. Is this intended?

https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=fortune&l=zdk8an-sf

**Comment by jwoertink** [comment]
Weird... No clue. 🤷‍♂️  @matthewmcgarvey may know, but it could also just be a typo somewhere on the techempower side... Here's the code https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Crystal/lucky if you get the itch to dig through.

**Comment by matthewmcgarvey** [comment]
This line needs to be updated https://github.com/TechEmpower/FrameworkBenchmarks/blob/d57aa8983b0c254ca1a8d0f9a8249abaf1a134fc/frameworks/Crystal/lucky/benchmark_config.json#L26

The value should just be "crystal" like kemals https://github.com/TechEmpower/FrameworkBenchmarks/blob/d57aa8983b0c254ca1a8d0f9a8249abaf1a134fc/frameworks/Crystal/kemal/benchmark_config.json#L25

Here's the docs on that config file https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Codebase-Framework-Files#benchmark-config-file

It's comparing to H20 because it's the fastest crystal framework. The idea of that measurement is that the framework is compared against the base that it's built on  to show how much "overhead" the framework adds. Seeing that kemal is faster than the crystal one means that it is not a very good measurement at the moment.

**Comment by sevensidedmarble** [comment]
Cool, well glad we figured it out.

>It's comparing to H20 because it's the fastest crystal framework.

Isn't H2O written in C though?

**Comment by robacarp** [comment]
@sevensidedmarble I think it's being compared to [h2o.cr](https://github.com/S-YOU/h2o.cr)

**Comment by jwoertink** [comment]
It looks like we've got this one answered, so I'm going to close the issue.
