### ISSUE TITLE
Cryptic compiler error when using `title()` method as variable in templates

### ISSUE THREAD

**Issue by vjousse** [luckyframework/lucky#1414]
**Describe the bug**
When using the `title()` function in a template as a variable `title` by mistake, the compiler displays a strange error message. 

**To Reproduce**
Don't define the `title` variable in your template and try to use it.

```crystal
h1 title, class: "text-5xl font-serif font-bold pt-20 pb-16 text-center"
```

You'll get an error message like this one:
```crystal
web          | In lib/lucky/src/lucky/tags/base_tags.cr:137:15
web          |
web          |  137 | tag_attrs.each do |key, value|
web          |                  ^---
web          | Error: undefined method 'each' for Nil
```

**Expected behavior**
A better error message saying, at least, that the problem is with the `title` variable/function.

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.26
 - Crystal version (`crystal --version`): 0.36.1
 - OS: Archlinux

**Comment by jwoertink** [comment]
Ok, so digging in more, this error comes up when you pass ANY type that isn't `String`. In the above error it says "each for Nil" because the return type of the `title()` method is `Nil`. You can get this same error by passing a `Time` object in.

```crystal
div user.created_at
```

```
web          | In lib/lucky/src/lucky/tags/base_tags.cr:137:15
web          |
web          |  137 | tag_attrs.each do |key, value|
web          |                  ^---
web          | Error: undefined method 'each' for Time
```

Where in this one, it says `Time`. 

So really what we need is an error message that says "HTML tags must pass a String" or something. I think if we do an override that catches a few of the common types (Nil, Time, Ints, Floats...) that may catch the bulk of these.
