### ISSUE TITLE
A lucky project dependency is causing ameba to show up in lib folder

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky#1524]
Maybe not a big deal, but I noticed in my project I generated with lucky cli that ameba is showing up in the `lib/` folder even though it's not a dependency and is not a transitive dependency either. When I run `shards prune` it is removed but added back as soon as I run `shards install` again.

<img width="463" alt="CleanShot 2021-06-08 at 20 28 01@2x" src="https://user-images.githubusercontent.com/17329408/121274246-16522b00-c898-11eb-8e60-bd3c56ccc1a6.png">

**Comment by jwoertink** [comment]
Weird... Would this be a shards bug? Or maybe all development dependencies always show up in lib unless you do `shards install --production`?

**Comment by jwoertink** [comment]
Looking in to this, it turns out it's Avram... Though, I'm still not sure why. Removed Avram from the list, and it doesn't show up. Ameba is a dev dependency of Avram, but it's also a dev dependency of ALL the Lucky shards. i created a new project with just Avram, and Ameba shows up. Then I made a project with just Habitat, and it doesn't show up....

**Comment by jwoertink** [comment]
Found the issue. Turns out this also exists in Lucky, and Carbon. The issue is that when the `postinstall` runs for each of these shards, it calls `shards build` from those directories. That will run a `shards install` within that directory which includes development dependencies.

To fix this, we need to add `--without-development` to each of these `shards build`.
