### ISSUE TITLE
datetime_input doesn't propagate time values correctly to operation

### ISSUE THREAD

**Issue by swilk19** [luckyframework/lucky#1530]
**Describe the bug**
When a model has a `Time` column, and the form data is provided via a `datetime_input`, only the `Date` portion of the input is saved; the `Time` portion is not persisted.

**To Reproduce**

> 1. Generate a Lucky project
> 2. Generate a browser action with a Time field
> 3. Change the `FormField` `render` method to use a `&.datetime_input()`
> 4. Save the model with a date and time value

**Expected behavior**
Both the date and time are persisted

**Screenshots/code**
As an example, here is some output I printed out from a project I was tinkering with with a project where a user can create a `Post`, which will go live at some specified future date and time:

`src/models/post.cr`:
```
class Post < BaseModel
  avram_enum Status do
    Pending
    Processing
    Completed
    Errors
  end

  table do
    column go_live_at : Time
    column status : Post::Status
    belongs_to user : User
  end
end
```

`src/components/posts/form_fields.cr`:
```
class Posts::FormFields < BaseComponent
  needs operation : SavePost

  def render
    mount Shared::Field, operation.go_live_at, &.datetime_input(autofocus: "true")
  end
end
```

`src/operations/save_post.cr`:
```
class SavePost < Post::SaveOperation
  # To save user provided params to the database, you must permit them
  # https://luckyframework.org/guides/database/validating-saving#perma-permitting-columns
  permit_columns go_live_at

  needs current_user : User

  before_save :go_live_must_be_future
  before_save :assign_user_id
  before_save :set_pending_status

  private def go_live_must_be_future
    go_live_at.value.try do |value|
      puts "Value: #{value}"
      puts "Time: #{value.hour}:#{value.minute}"
      pp params
      if value.to_utc < Time.utc
        go_live_at.add_error "must be in the future"
      end
    end
  end

  private def assign_user_id
    user_id.value = current_user.id
  end

  private def set_pending_status
    status.value = Post::Status.new(:pending)
  end
end
```

The printed values contain details like the following from some sample input:

```
{URI::Params(
    @raw_params=
     {"_csrf" => ["some csrf token"],
      "_method" => ["put"],
      "post:go_live_at" => ["2021-07-08T04:04"]})} <--- Time details seem to be coming in from the form, but no time zone?
```
when I print the parsed value (via `go_live_at.value.try` block):
```
Value: 2021-07-08 00:00:00 UTC
```
The time portion of the date is gone, and this matches to the persisted values I see after the save completes successfully. Not sure if I missed a setup piece here but what I have seems like it should work

**Versions (please complete the following information):**
 - Lucky version (check in shard.lock): 0.27.2
 - Crystal version (`crystal --version`): 1.0.0
 - OS: Ubuntu/WSL

**Additional context**

**Comment by jwoertink** [comment]
Hey @swilk19, thanks for reporting this! I think I have an idea of why this is happening, but would you be able to try something for me?

In your `config/database.cr` file, there's a line that says `Avram.configure`. In that block, can you add

```crystal
Avram.configure do |settings|
  settings.database_to_migrate = AppDatabase

  # In production, allow lazy loading (N+1).
  # In development and test, raise an error if you forget to preload associations
  settings.lazy_load_enabled = Lucky::Env.production?

  # Add this line:
  settings.time_formats << "%Y-%m-%dT%H:%M:%S"
end
```

I'm not sure if the HTML input includes timezone on it, or if there's even a way to specify that... But if this fixes just passing over the time, then I'll at least know what the issue is.

**Comment by swilk19** [comment]
I tried this out, unfortunately got the same results on the create/edit page saves

**Comment by jwoertink** [comment]
Bummer... 😕  Thanks for giving that a shot! I'll have to look in to this more and figure out what's going on. Most likely it's an issue related to [Avram](https://github.com/luckyframework/avram/) specifically since that's where the Time parsing happens. 

I'll leave this issue open, but I'm going to open one on Avram as well just to make sure it's tracked in both areas.

**Comment by swilk19** [comment]
I looked at my input more closely and found the issue, the input doesn't include seconds, only hours and minutes. I tried again with this:
```
Avram.configure do |settings|
  settings.database_to_migrate = AppDatabase

  # In production, allow lazy loading (N+1).
  # In development and test, raise an error if you forget to preload associations
  settings.lazy_load_enabled = Lucky::Env.production?

  settings.time_formats << "%Y-%m-%dT%H:%M"
end
```
and now the hours/minutes are persisted correctly. Appreciate the help!

**Comment by jwoertink** [comment]
Awesome! Glad you got it working.

Ok, so step one is we need to document that option. https://github.com/luckyframework/lucky_cli/issues/643 Then after figuring out https://github.com/luckyframework/lucky/pull/1519 the input setup stuff will be handled directly in Lucky.

**Comment by stephendolan** [comment]
I'm so confused, because this was definitely working in LuckyCasts when I submitted https://github.com/luckyframework/avram/pull/603

Just verified that hours/minutes still weren't saving, though, and the new regex without the seconds did indeed work. Regardless of next steps with params/documentation, I'm going to dig into a PR to Avram to correct this by default if possible.
