### ISSUE TITLE
Add "lucky exec"

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#198]
ICR and  `crystal play` are too brittle because they recompile every time. So for example, if you make an HTTP request, or delete/update a record it will try to do it every time you enter a new line. Not good.

Instead do lucky exec luckyframework/cli#2 (comment)

So basically `lucky exec 'UserQuery.new.find(1).delete` would run `crystal eval 'require app.cr; UserQuery.new.find(1).delete`

Even better would be to open a temporary file or something. Similar to the package I linked to in the first comment. But it's fine to get a first version in without that if it's too hard.

**Comment by paulcsmith** [comment]
There is also this cool looking package: https://github.com/veelenga/vicr It'd be nice to use w/o vim so maybe we could fork it and contribute some options so you can use nano, emacs or whatever you want

**Comment by jwoertink** [comment]
What if icr didn't run like that each time? I've been thinking about fixing that issue anyway. Unless crystal gets an official repl, anything we use is gonna have it's pros and cons, but I'm thinking since ICR already takes care of a lot, if this major issue was fixed, would it be a viable option again? Or are you looking for lucky to have it's own custom code running?
