### ISSUE TITLE
Unable to create a new lucky project after rename

### ISSUE THREAD

**Issue by nicohvi** [luckyframework/lucky#256]
Hi there!

It seems that the renaming of `LuckyWeb` to `Lucky` has caused some problems for creating new Lucky projects.

Steps to reproduce:

```lucky init <name>```

Yields the following error:

```
Error shard name (lucky) doesn't match dependency name (lucky_web)
```

Lucky 0.6.2
Crystal 0.23.1 (2017-10-12) LLVM 4.0.1

**Comment by paulcsmith** [comment]
@nicohvi thanks for reporting this! Are you on Linux? I wonder if you checked out the latest Lucky CLI from master. That may have been the problem because that version did not work. It had to be the tag from the released version. 

I’ll take a closer look, but this issue should be resolved soon because I’m about to release all new versions of Lucky and Lucky CLI :D

**Comment by paulcsmith** [comment]
This should be fixed with the newest release. If you're on macOS run `brew upgrade lucky` to get the newest version. If you're on Linux you'll need to `git pull` the latest version of lucky and then `git checkout v0.7.1` (see instructions in the guides: http://luckyframework.org/guides/installing/#install-lucky

Let me know if that works for you!

**Comment by nicohvi** [comment]
Thank you for the very swift response, @paulcsmith! I was indeed using macOS and upgrading to `0.7.1` did the trick 👍
