### ISSUE TITLE
Consider switching to webpack using Laravel mix 

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#259]
https://scotch.io/tutorials/using-laravel-mix-with-webpack-for-all-your-assets
https://laravel.com/docs/5.5/mix

Normal webpack is a pain to setup. This might make webpack a viable option for Lucky. Will have to try it out first. 

It must:

* be simple to configure
* have os notifications on failed build
* asset fingerprinting for all assets, including images and fonts (https://github.com/JeffreyWay/laravel-mix/releases/tag/v1.0.0 - see example of copying and versioning, https://github.com/JeffreyWay/laravel-mix/issues/270#issuecomment-345502119, https://github.com/JeffreyWay/laravel-mix/issues/1193)
* must fingerprint assets in CSS (like background images)
* allow full customization for people that need advanced webpack features
* trigger recompiles and browser sync reload when using glob imports in PostCSS

```
// File versioning
.version(['public/assets'])
```

**Comment by krishandley** [comment]
Had a quick go at getting laravel mix working with lucky, so thought I would report my findings.

## Summary

For easier switching from or between brunch, moving to npm scripts instead of bin/compile_assets, for easier place to configure commands.

Config would be simpler if manifest path was configurable.

**Note:** Won't compile if you were using .pcss files before, these will need renaming to .scss

I think it ticks all your boxes except the issues listed at the end. I'd be happy using this anyway.

**Bonus:** My production build of a JS file with only rails ujs + turbolinks is also only 49kb minified instead of 334kb from the brunch production build. 👍 

## Setup

```bash
yarn add laravel-mix
cp node_modules/laravel-mix/setup/webpack.mix.js ./
```
If you were using brunch before, you might need to yarn remove a few packages.

Update webpack.mix.js with the following (Assumes you are using sass + .scss ext) change as required

```js
var mix = require('laravel-mix');
var fs = require('fs');

mix
  // JS entry file
  .js('static/js/app.js', 'public/js')
  // SASS entry file
  .sass('static/css/app.scss', 'public/css')
  // Set public path so manifest gets output here
  .setPublicPath('public')
  // Copies static assets
  .copyDirectory('static/assets', 'public/assets')
  // Hash all the things
  .version(['public/assets'])
  // After build succeeded
  .then(() => {
    /*
      Lucky expects the manifest file to be called manifest.json so we
      need to rename the file AFTER the versioning has happened

      Using mix.copy does this before the versioning not after

      To get rid of this luck would need a config option for the manifest
      like phoenix i.e.

      config :my_app, MyApp.Endpoint,
        cache_static_manifest: "priv/static/mix-manifest.json"
    */
    fs.rename('public/mix-manifest.json', 'public/manifest.json', err => {
      if (err) console.log('ERROR: ' + err);
    });
  });
```

## Remove bin/compile_assets

`rm bin/compile_assets`

Add this to package.json instead

```json
{
  "scripts": {
    "heroku-postbuild": "yarn prod",
    "dev": "webpack --progress --hide-modules --color --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "webpack --watch --progress --hide-modules --color --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "NODE_ENV=production yarn run webpack --progress --hide-modules --color --config=node_modules/laravel-mix/setup/webpack.config.js"
  }
}
```

## Updates

Procfile.dev

* change `assets: bin/compile_assets watch`
* to `assets: yarn watch`

bin/setup

* change `bin/compile_assets build | indent`
* to `yarn dev | indent`

# Issues

## asset(...)

Lucky is adding a slash at the beginning of assets in the manifest

https://github.com/luckyframework/lucky/blob/bccde2d7d1d1c1723f6aa5aa9da6a582c43a6d7d/src/lucky/asset_helpers.cr#L9

### Temporary fix

```crystal
css_link asset("/css/app.css").sub("//", "/")
js_link asset("/js/app.js").sub("//", "/")
```

## No hashes for paths inside css files

Might need something like this https://hexdocs.pm/phoenix/Phoenix.Digester.html to run afterwards

## No SASS glob imports

Not fussed myself, I've always done this manually anyway. I tried to get it working with with a few different plugins but no luck.

## Change to importing css from node_modules

You'll need to do this instead

```css
@import "~normalize.css";
```

## --progress

If you add this option your console will be spammed when running lucky dev

**Comment by paulcsmith** [comment]
@krishandley This is some incredibly helpful stuff. Thanks a ton for being so thorough. I'm going to try this out in one of my projects in the next few weeks and this will really help get me started. I'll post here with details and a link to the relevant PR in the lucky_cli repo if I move forward with the switch

**Comment by jwoertink** [comment]
@paulcsmith this issue is done now, right?

**Comment by paulcsmith** [comment]
I’m going to wait to test it out a bit more, but yes it is super close!!

**Comment by paulcsmith** [comment]
Thank you so much @krishandley! Your comment was immensely useful.

Here are the guides for the new asset handling in Lucky 0.10.0! https://luckyframework.org/guides/asset-handling/

**Comment by krishandley** [comment]
Works nicely! Glad it was helpful.
