### ISSUE TITLE
Wrong escaping of Actions in links

### ISSUE THREAD

**Issue by hanneskaeufler** [luckyframework/lucky#301]
This is a failing test for `spec/lucky/link_helpers_spec.cr`.

```crystal

class LinkHelpersWithParam::Index < Lucky::Action
  param page : Int32?
  action { render_text "foo" }
end

describe Lucky::LinkHelpers do
  it "does not escape paths with query params" do
    view.string_path_with_param.to_s.should contain <<-HTML
    <a href="/link_helpers_with_param?page=4">With Param</a>
    HTML
  end
end
```
Which fails with

```
1) Lucky::LinkHelpers does not escape paths with queury params
     Failure/Error: view.string_path_with_param.to_s.should contain <<-HTML

       Expected:   "<a href=\"/link_helpers_with_param?page&#61;4\">With Param</a>"
       to include: "<a href=\"/link_helpers_with_param?page=4\">With Param</a>"

     # spec/lucky/link_helpers_spec.cr:94

Finished in 29.84 milliseconds
205 examples, 1 failures, 0 errors, 0 pending
```
See the `=` which is HTML escaped to `&#61;` which is not quite what I want. Urls for `route`s are already url escaped, no need to html escape them once more. Not quite sure where to best fix it and wont have any time the coming days so here is an issue :)

**Comment by paulcsmith** [comment]
@hanneskaeufler I did some research on this and it seems it is ok to HTML escape these. It may even be good because it makes sure there aren't any characters that would cause malformed HTML. 

As you can see here, it looks like the browser unescapes it correctly:

<img width="324" alt="screen shot 2017-12-15 at 10 12 41 pm" src="https://user-images.githubusercontent.com/22394/34066894-33b4770e-e1e5-11e7-8d74-007c59fb3ba6.png">

Was this causing an issue for your web app? If not I'll close this because I think it is correct behavior

**Comment by paulcsmith** [comment]
Actually, I'm going to close this for now (easier to keep track of where things are at), but please reopen it and comment if it is causing a problem in your app. If it is, can you point me to the line that's causing issues and I'll happily take a look :)

**Comment by hanneskaeufler** [comment]
Hm you are absolutely right. Thanks for closing this. I think weirdness `html.should contain "<a href=\"/?page&#61;2\">Next page &raquo;</a>"` could be solved be better spec helpers/or I should debate whether or not I should write such a test.

**Comment by paulcsmith** [comment]
Yeah I think some test helpers that parse html could help with that. It’s on the roadmap. Though I’m not sure how valuable testing links is, since the compiler would likely catch any errors since the route helpers are type safe. A system test using something like capybara may be more helpful. I haven't tried it but there is a library called garnet spec that amber framework has might be worth a look
