### ISSUE TITLE
Support GraphQL

### ISSUE THREAD

**Issue by kalicki** [luckyframework/lucky#340]
REST or GraphQL or Hybrid?
Trend in this new year is the migration of great webservices to GraphQL, it would be interesting to explore this in Lucky

**Comment by paulcsmith** [comment]
@kalicki Lucky supports REST web APIs (I just need to finish writing the guides). I think GraphQL would be super cool, but might be better as a separate lib. I'd love to do something in the Lucky repo, but it might be a bit since I need to finish a few more things first.

If someone from the community wants to make something fro GraphQL that works with Lucky and LuckyRecord, I'm happy to help with API design and working through the integration.

**Comment by kalicki** [comment]
Thanks for reply =)
Idea: http://graphql-ruby.org

**Comment by paulcsmith** [comment]
I'm going to close this as an issue to keep focused, but someone is working on a GraphQL shard. Once it is done I'll work on making it really easy to use in Lucky!

**Comment by itsezc** [comment]
@paulcsmith Any updates on this matter?

**Comment by jwoertink** [comment]
@itsezc There hasn't been any movement on this. I don't know of anyone actually using GraphQL, but if you're familiar with it, it would be great to see what that would look like in Lucky. What sort of things would be needed to make that happen? Feel free to hop in the [chat](https://gitter.im/luckyframework/Lobby) to hash out specs around this.
