### ISSUE TITLE
generate_tag_methods inserts superfluous "do" in some cases

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#422]
generate_tag_methods inserts a superfluous "do" statement if it is invoked inside of a macro definition, and the tag has a parameter.

Notice below that the "tr" without a parameter has a "do" after it, as you would expect, and the "tr" with a parameter does not, and this code compiles. It won't compile if I put a "do" before the comment.

```
class Users::X < MainLayout
  macro row
    tr do
    end

    tr class: "foo" # Notice, no "do" here.
    end
  end

  def content
  end
end

```

**Comment by BrucePerens** [comment]
Actually, I'd like to know how to do things like this without macros :-)

private macro row(method, note, type = text)
    tr do
      th { label_for f.{{method}} }
      td { {{type}}_input f.{{method}} }
      td { errors_for f.{{method}} }
      td {{note}}
    end
  end

**Comment by paulcsmith** [comment]
Ahh, yes that is a tricky one since you need the macro to build the method definition. There is a way to get around this, but calling the method is a tad bit more involved. It will be introduced in the next version of Lucky. Here's what it looks like!

* This defines the `field` helper. You can add that to your components directory and customize it to use `tr` and `td` like you did: https://github.com/paulcsmith/lucky-auth/blob/master/src/components/shared/field.cr
* Then use it in your views like in this example: https://github.com/paulcsmith/lucky-auth/blob/76257e059ffdc363e0209b9853a3402e9bb5bf69/src/pages/password_resets/new_page.cr#L11-L16

It is a *bit* more verbose but requires no stacktrace and is super flexible since you can pass options to the input pretty easily, like `autofocus` in the example above. 

Does this work for you?

**Comment by BrucePerens** [comment]
That's not bad. You might some thought into how you might want to internationalize that in the future. My ruby version generates internationalization for the label and the note. I have a Ruby Gem, [i18n-edit](https://github.com/BrucePerens/i18n-edit) which allows you to type internationalization strings into the rendered web pages of a running application, just by right-clicking on the text. This makes them very easy to enter.

**Comment by paulcsmith** [comment]
I18n is likely going to be after 1.0 since not everyone uses it, but I do have some ideas for it. Some criteria for whatever Lucky uses: 

* Compile error if a translation is missing. 
* Compile error if you forget to translate a string (configurable so if you don't want I18n you don't have to)

Ideally it will also allow for writing plain English in the view, similar to how `gettext` with Elixir: https://github.com/elixir-lang/gettext

This makes it easier to get started and makes views more readable IMO.

My thought is that it will look something like this:

```crystal
# I like t better than gettext. 
link t("Sign Up"), to: SignUps::New
```

Then you can run a task to extract .po files like in Elixir

**Comment by paulcsmith** [comment]
BTW editing translations in the page is an awesome idea! I like that a lot

**Comment by paulcsmith** [comment]
I just tried this and it appears to work ok now so I'm going to go ahead and close this
