### ISSUE TITLE
Path without starting slash compiles fine, but yields 404 on visiting intended path

### ISSUE THREAD

**Issue by neurodynamic** [luckyframework/lucky#444]
```
  get "sign_up" do
    text "Render something in Users::New"
  end
```

This code compiles fine, but creates an impossible `sign_up` route instead of a working `/sign_up` route. Easy mistake to make. Some sort of error on this kind of thing would definitely be helpful.

**Comment by paulcsmith** [comment]
I totally agree! If you'd like to try to do this I can give you some pointers along the way, but if you don't have time I can tackle this in the next few days.

**Comment by neurodynamic** [comment]
@paulcsmith I'd be happy to give it a shot. Do you think it'd be better to have the behavior be raising something like a `BadRoute` exception with an appropriate message, or to modify the route to automatically add the slash if it's missing (assuming there aren't circumstances where that would break something that otherwise worked?)?

**Comment by paulcsmith** [comment]
I think it would be best to raise an error at compile time so that all the routes are consistent in the code. To do this you'll need to modify the `get/post/put/delete` macros:

* They are located here: https://github.com/luckyframework/lucky/blob/master/src/lucky/routeable.cr#L21
* At the very top of the method you can do something like this:

```crystal
{% unless path.starts_with?("/") %}
  {% raise "paths must start with '/'" %}
{% end %}
```

You can't really have an automated test for this (AFAIK) since it will cause a compiler error. So to test it you'll have to change one of the actions in spec/action_spec.cr to not start with a slash and see what the error looks like. I hope this makes sense. Ping me if you run into any trouble, and thanks for taking a shot at this!
