### ISSUE TITLE
Lucky engine

### ISSUE THREAD

**Issue by sebyx07** [luckyframework/lucky#494]
How would be implemented Rails like engines in Lucky?
Engines are really useful,  ex: https://github.com/sferik/rails_admin

**Comment by matthewmcgarvey** [comment]
Asking to add Rails like engines is a bit loaded. If I'm thinking about what you mean by this I'd say:
- the ability to add routes to an app through a library
- the ability to add resources other than Ruby/Crystal (html, javascript)
- the ability to introspect or (at the very least) generate functionality based on the app the engine is added to

While I think Rails engines are very powerful, we can pretty much do the same thing in Lucky by just adding regular shards. Refer to https://github.com/luckyframework/breeze as it adds endpoints, tasks, views, migrations, models.

You won't ever see a `lucky-jquery` shard though since we have don't have a custom asset pipeline.

Introspection is definitely going to be a problem/hurdle though. An admin that can introspect models and generate views based on them sounds like a tough task. Maybe somebody will look into it at some point?
