### ISSUE TITLE
Make nested_actions id explicit

### ISSUE THREAD

**Issue by snadon** [luckyframework/lucky#497]
Sometimes `id` is confusing. Prefacing it with the model name can resolve this (e.g.: `user_id`).

**Comment by paulcsmith** [comment]
If someone wants to tackle this, the class that handles route inference is here: https://github.com/luckyframework/lucky/blob/master/src/run_macros/infer_route.cr

The rough idea would be:

* Change https://github.com/luckyframework/lucky/blob/500e4bc28786722700672c398b768b3937b204cd/src/run_macros/infer_route.cr#L56-L69 so that it uses the singularized resource name + id, instead of just id
* You can change it based on whether the route is nested with the helper method `if nested_route?`
* You can get the singularized resource name with something like `LuckyInflector::Inflector.singularize(resource)`

**Comment by paulcsmith** [comment]
Closed in https://github.com/luckyframework/lucky/issues/659
