### ISSUE TITLE
Unexpose not working

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/lucky#530]
Unexpose isn't yet documented so it has "magic" status at the moment. Create a new project with these files:

src/actions/home/index.cr

```
class Home::Index < BrowserAction
  include Auth::SkipRequireSignIn
  unexpose current_user

  get "/" do
    render IndexPage
  end
end
```

src/pages/home/index_page.cr

```
class Home::IndexPage < MainLayout
  needs current_user : User?
  def content
  end
end
```

At build time, I see this:

```
web    | macro didn't expand to a valid program, it expanded to:
web    | 
web    | ================================================================================
web    | --------------------------------------------------------------------------------
web    |    1.     
web    |    2.       def initialize(
web    |    3.         
web    |    4.           
web    |    5.           
web    |    6.           
web    |    7.            @context : HTTP::Server::Context,
web    |    8.         
web    |    9.           
web    |   10.           
web    |   11.           
web    |   12.            @current_user : User,
web    |   13.         
web    |   14.           
web    |   15.           
web    |   16.           
web    |   17.            @current_user : User | ::Nil,
web    |   18.         
web    |   19.         )
web    |   20.       end

```

It seems the entire reason to use unexpose here is that we're changing the type of `current_user` from `User` to `User | Nil`. Wouldn't it be better to catch the declaration in the `needs` macro, and replace the declaration generated into the `initialize` function, without having to `unexpose?`

**Comment by paulcsmith** [comment]
@BrucePerens Thanks for opening this. `unexpose` isn't there to set it to `nil` but to stop passing it to the page at all. So if you do `unexpose` you need to remove the `needs` from the page.

So `unexpose` is working correctly. The reason it didn't compile is that you have `needs current_user` twice. Once in the `MainLayout` and then again in your `IndexPage`

What are you trying to do? Maybe I can help.

I'll close this for now since it isn't a bug, but feel free to comment here or hop on Gitter. I'll be happy to help

**Comment by BrucePerens** [comment]
OK, close this one and I will file another bug with the complaint about this all being too spooky.
