### ISSUE TITLE
`lucky gen.action.api` should generate actions under `src/actions/api/`

### ISSUE THREAD

**Issue by mikeeus** [luckyframework/lucky#547]
When working on [generating apis with JWT auth](https://github.com/luckyframework/lucky_cli/pull/223) we namespaced the api actions under `src/actions/api`. I think we should generate api actions in the same place for consistency.

**Comment by paulcsmith** [comment]
I think this should be up to the user. If they want to namespace them they can do Api::<ActionName>

Because maybe some people don’t want to namespace it, or they have some other namespace. If we default it to Api then they can’t change it. 

Does that make sense or would that flexibility hurt not really be useful?

**Comment by mikeeus** [comment]
I forgot that they can namespace it be the `Api::` prefix, that makes sense thanks.

**Comment by paulcsmith** [comment]
Perfect!
