### ISSUE TITLE
Unexpected byte 0x2e at 3 (Base64::Error)

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#636]
This is actually related to the latest changes to cookies.

If you're running a version of lucky from bf7a922c73396a3dc150a5c5106bff7bdcbaed84 or before, and you boot your app, you'll have a cookie set using the old method. Then upgrading and booting the app before clearing any cookies, you'll get this error:

```
Unexpected byte 0x2e at 3 (Base64::Error)
  from /usr/local/Cellar/crystal/0.26.1/src/base64.cr:0:80 in 'decode'
  from lib/lucky/src/lucky/cookies/processors/encryptor.cr:17:17 in 'read'
  from lib/lucky/src/lucky/cookies/processors/encryptor.cr:5:5 in 'read'
  from lib/lucky/src/lucky/context_extensions.cr:11:5 in 'cookies'
  from lib/lucky/src/lucky/context_extensions.cr:18:32 in 'session'
  from lib/lucky/src/lucky/session_handler.cr:13:8 in 'write_session'
  from lib/lucky/src/lucky/session_handler.cr:8:5 in 'call'
  from /usr/local/Cellar/crystal/0.26.1/src/http/server/handler.cr:24:7 in 'call_next'
```

You can try this by 
1. booting an app locally with an older version of lucky. 
2. Go to `myapp.lvh.me:5000` so the cookie gets set.
3. stop the server, and upgrade lucky
4. boot the new server
5. refresh that page on `myapp.lvh.me:5000`. 

To fix the error, just clear out all cookies.

cc. @edwardloveall

**Comment by paulcsmith** [comment]
I believe I figured out what is going wrong

1. When you have an existing session/cookie (like when you already had a Lucky app and are trying to upgrade), Lucky tries to Base64 decode and decrypt the session/cookie. This is expected and can be fixed by deleting the session/cookie in your browser. We'll come up with a better way to handle this.
2. The other issue is the one @jayroh mentioned where even after deleting cookies/sessions it will work for one page load then fail again. This is because the new cookies/session implementation eager loads all cookies and tries to decrypt them. The problem with that is sometimes third party scripts add cookies and those will never work with Lucky encryption. So every time a page loads, the cookie is set, then on subsequent load Lucky fails because it cannot decrypt the cookie.

I believe the fix to item 2 is to lazy load cookies. That way third party cookies are untouched and we don't have errors trying to decode and decrypt them.

**Comment by paulcsmith** [comment]
I'm thinking one way to address 1 (and make better errors for 2) is to add a version string to the beginning of the cookie and the session.

When Lucky tries to load a session w/o the version string it ignores it and sets the session to empty. That way on subsequent. This will also make it easier to make changes in the future that are backwards compatible (maybe we want to change the encryption/decryption algorithm for example). This would also allow for better errors when you try to access a cookie that is not encrypted (like one from a third party script). Lucky could look at the value, see there is no version string, and let you know that it is a third party cookie. Maybe there is even a method like `cookies.get_raw("my_third_party_cookie")` that will do no decryption and let you read any cookie as-is
