### ISSUE TITLE
Route helpers rendering full urls with server.url instead of app.base_uri

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky#684]
If you alter the App#base_uri method, manually rendering a URL (for example, an oauth callback) does not correctly update because it [uses the settings.base_uri instead](https://github.com/luckyframework/lucky/blob/master/src/lucky/route_helper.cr#L12).

I found myself hitting this because I'm running the server behind ngrok to test oauth flows, and unable to use the Lucky::Action.route.url method.

Is there an obvious way around that, or is this a bug?

**Comment by paulcsmith** [comment]
@robacarp How did you modify `App#base_uri`? I'm curious what it looks like to see if there is a way around what you're running in to. 

I'm guessing what you want is to keep `App#base_uri` as-is because that is what the app code is running on so it is typically `localhost:5000` in dev. What you probably want to change is the route helper in `config/route_helper.cr`. That is what the `.url` and `url_without_query_params` uses when building links.

This is also what you'd want to use in production to set the domain that Lucky uses when generating URLs.

**Comment by robacarp** [comment]
@paulcsmith Interesting. By my count, that makes 3 places urls are stored:

- [config/server.cr](https://github.com/robacarp/bare_lucky_repo/blob/master/config/server.cr#L2-L12)
- [src/app.cr](https://github.com/robacarp/bare_lucky_repo/blob/master/src/app.cr#L37-L39)
- [config/route_helper.cr](https://github.com/robacarp/bare_lucky_repo/blob/master/config/route_helper.cr#L3-L9)

Modifying server.cr breaks the server. It won't boot, with the error:

```diff
Lucky::Server.configure do |settings|
  if Lucky::Env.production?
    settings.secret_key_base = secret_key_from_env
    settings.host = "0.0.0.0"
    settings.port = ENV["PORT"].to_i
  else
    settings.secret_key_base = "1oIOjfgoUqFaaTEj+bDeiryumevfAMqknm+cmwhZP48="
    # Change host/port in config/watch.yml
    # Alternatively, you can set the PORT env to set the port
-   settings.host = Lucky::ServerSettings.host
+   settings.host = "xxxxxxx.ngrok.io"
    settings.port = Lucky::ServerSettings.port
  end
end
```

```
web    | Listening on https://xxxxxxx.ngrok.io
web    | Unhandled exception: bind: Can't assign requested address (Errno)
```

So I modified the next place I found, app.cr:

```diff
class App
  # ...
  def base_uri
-    "http://#{host}:#{port}"
+   "https://xxxxxxx.ngrok.io"
  end
  # ...
end
```

Which changes _some things_:

```
web    | ./config/server.cr has changed
web    | compiling...
web    | Listening on https://xxxxxxx.ngrok.io
```

That's actually pretty handy because I can open that from the terminal and have the site exposed on the right domain but, as you point out, doesn't change the way URLs are rendered without a bunch of other hackery.

As you were able to help me in chat, using the Action#url and modifying `config/route_helper.cr` made it all work.

**Comment by paulcsmith** [comment]
Thanks for the thorough explanation of what didn't work and what did. Really src/app.cr shouldn't be modified by users except for the middleware. I'm thinking that instead of the current implementation I will create a `Lucky::App` class that `App` will inherit from and have just a single setting for the middleware array. That way it is less confusing about what should be user editable and what shouldn't be. I'm thinking of also adding a comment to `config/server.cr` that says to change the host of generated links in `config/route_helper.cr` to help point people in the right direction.

What do you think?

**Comment by robacarp** [comment]
Those are both great ideas, thanks!
