### ISSUE TITLE
Get rid of `show_debug_output` and make error handling more intuitive

### ISSUE THREAD

**Issue by HarrisonB** [luckyframework/lucky#719]
Perhaps I don't understand this setting, but just because you want to see the debug info doesn't mean you don't want error handlers to behave as they normally do (giving correct status codes, response bodies, etc.)

**Comment by paulcsmith** [comment]
I think you understand it but it’s just confusing 😂 

Thank you for opening this. I want to rework this so that errors you handle are always displayed and you only get the stacktrace for unhandled ones. I’m open to ideas here but I think what I’d like to do is rename Errors::Show to UnhandledErrors::Show and then have a module called RescueErrors that is included in the base actions that lets you rescue errors and display them

Still need to figure out the internals but that’s a high level view of how I think it would work. Thoughts?

**Comment by HarrisonB** [comment]
I think I understand a bit, but I have some questions:

* Would it send the stacktrace to STDERR? Or to your logger?
* Which errors would `RescueErrors` catch? Does it have priority over `UnhandledErrors::Show`?

**Comment by paulcsmith** [comment]
Good question. I'm not sure though. I think for the stack trace it'd print to the logger. 

Your second question makes me think there should not be an `UnhandledErrors::Show`...because the division is unclear. I might need to rethink that a bit so there is *just* `RescueErrors`. Basically I want one place where you define error handling, but there also needs to be a way for unhandled exceptions to bubble up when in dev. I'm not 100% sure of the best way to do this yet

**Comment by HarrisonB** [comment]
Why not just put that behavior in ResuceErrors or some base it inherits from but output dependent on env?

**Comment by paulcsmith** [comment]
I think that might work well! Still trying to figure out how that would work with errors outside of actions though. For example, what if there is an error outside of an action, like in a middleware. If the rescued errors are in the base action classes they won't be caught. So maybe we do need two separate ones. Or maybe instead of a mixing it is a class that can be used by both actions *and* an ErrorHandler

```crystal
class BrowserAction
  rescue_using RescueErrors
end

# and in the ErrorHandler middleware
Lucky::ErrorHandler.new(rescue_using: RescueErrors)

class RescueErrors < Lucky::ErrorAction

    def handle_error(error : Exception)
    if Lucky.settings.show_debug_output?
      render_exception_page
     else
      Lucky.logger.error(error.inspect_with_backtrace)

      message = "An unexpected error occurred"

      json Errors::ShowSerializer.new(message), status: 500
  end
end
```

Very rough example but it might work

**Comment by paulcsmith** [comment]
Or actually maybe that could just be what Errors::Show is today but just with the `show_debug_output` call in the `handle_error` method

**Comment by HarrisonB** [comment]
> Or actually maybe that could just be what Errors::Show is today but just with the `show_debug_output` call in the handle_error method

Yes! Agree 100%.

**Comment by paulcsmith** [comment]
One thing that could be nice about having `rescue_using` is that you could have different actions rescue differently. For example V1 of an API and V2 might have different ways of rescuing errors. With `Errors::Show` that it harder to do...but that can come later :)

For now I think converting Lucky::ErrorHandler to always call the action and having the action itself decide whether to show debug errors or not is a good solution and is much better than what we have now!

If you have time would you like to tackle this? I'm happy to provide guidance. No pressure, just curious :)

**Comment by paulcsmith** [comment]
I think it would be roughly:

* Remove conditional and always call error action: https://github.com/luckyframework/lucky/blob/b671ad32e7d3c9cecd14f8ec5ccfdb232d71786b/src/lucky/error_handler.cr#L16-L20
* https://github.com/luckyframework/lucky_cli/blob/f87710291ef066a665b05f75105fbe370c294016/src/web_app_skeleton/src/actions/errors/show.cr.ecr#L29-L30 should render the exception page if `Lucky::ErrorHandler.settings.show_debug_output` is set. I think we can expose https://github.com/luckyframework/lucky/blob/b671ad32e7d3c9cecd14f8ec5ccfdb232d71786b/src/lucky/error_handler.cr#L29-L34 as public and call it from `Errors::Show`. Something like `Lucky:ErrorHandler.render_exception_page(context, error)` in the `handle_error`

**Comment by HarrisonB** [comment]
I'll see what I can do 😄

**Comment by paulcsmith** [comment]
Closed by #318

**Comment by HarrisonB** [comment]
Is that the correct PR?

**Comment by paulcsmith** [comment]
Nope. Oops ;) that’s what I get for doing it in my phone
