### ISSUE TITLE
Add `before` and `after` for `Lucky::ErrorAction`s

### ISSUE THREAD

**Issue by HarrisonB** [luckyframework/lucky#736]
This is nice for
* adding headers that should be present for every response
* sending automated reports to a bug tracking system
* any operation that should be done in response to an erroneous response

**Comment by jwoertink** [comment]
Maybe having this would also solve https://github.com/luckyframework/lucky/issues/500 ?

**Comment by HarrisonB** [comment]
@paulcsmith Are you working on this? Otherwise, I'd like to give it a shot.

**Comment by paulcsmith** [comment]
Nope I haven’t started on it! I’d love to see what you would do with it. 

Maybe an ErrorAction is just like a regular action with a slightly different “call” method? Just a quick thought. Feel free to reach out if you want to discuss anything

**Comment by paulcsmith** [comment]
I believe the new Errors::Show will cover these vases. There is a “report” method, and an error_json and error_html method where methods and such can be added. Let’s see how far this gets us and reopen this if needed. 

I’d prefer to keep error actions as thin as possible so that there is less room for introducing bugs while handing errors. I like the idea that ErrorActions are pretty lightweight so less room to mess things up in accident 

But we can definitely add this if what we have is still not enough!
