### ISSUE TITLE
Investigate this serializer issue

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#746]
https://gist.github.com/notbryant/2ee53de8c167f9f449bcedc587c3c716

May just need better docs? Or maybe different `require` order?

**Comment by jwoertink** [comment]
Just got this error too... I'm gonna dig in

**Comment by paulcsmith** [comment]
Thanks. I really appreciate it

**Comment by jwoertink** [comment]
Ok, so it turns out this is more of a crystal thing; however, I don't think it's really a bug. We do need to update documentation to fix this though.

[In the docs](https://luckyframework.org/guides/writing-json-apis/#create-a-serializer) we show to define a serializer like this:
```crystal
class Api::Articles::Show < ApiAction
  route do
    article = ArticleQuery.new.find(id)
    json Articles::ShowSerializer.new(article)
  end
end
```

The problem is this would not compile and throw `undefined constant Articles::ShowSerializer`. This is because we're in the `Articles` namespace at this point, so `Articles` is local to this namespace. To fix this, you just need to scope to the parent namespace with `::Articles::ShowSerializer.new(article)`. It's not exactly "pretty", but it is proper. Since that gist above seems to be gone now, I'm assuming it was a similar issue. I do remember him saying renaming it fixed the issue.

Recap:

## Doesn't compile
```crystal
class Api::Tacos::Index < ApiAction

  get "/api/tacos" do
    json({tacos: Tacos::IndexSerializer.new})
  end
end
```
```text
in src/actions/api/tacos/index.cr:4: undefined constant Tacos::IndexSerializer

    json({tacos: Tacos::IndexSerializer.new})
                 ^~~~~~~~~~~~~~~~~~~~~~
```

## Does compile
```crystal
class Api::Tacos::Index < ApiAction

  get "/api/tacos" do
    json({tacos: ::Tacos::IndexSerializer.new})
  end
end
```

**Comment by paulcsmith** [comment]
Nice! Thank you for finding that

Ah I see. Maybe we could recommend doing `Api::Tacos::IndexSerializer` so that you don't need to do the `::Tacos`. You can just do `IndexSerializer`...what do you think?

Also what do you think about opening an issue in Crystal lang about Crystal helping the user out a bit more. I feel like if it doesn't find it in that namespace it should check if there is one at the top level and suggest it `Crystal looked in Api::Tacos::IndexSerializer. Did you mean ::Tacos::IndexSerializer?`

This has happened to me before and stumped for awhile until I realized what was going on

**Comment by paulcsmith** [comment]
Also the error message is wrong (Crystal bug) because it says `undefined constant Tacos::IndexSerializer` but really it *should* say `undefined constant Api::Tacos::IndexSerializer`. This is part of what made this hard to track down IMO :(

**Comment by jwoertink** [comment]
I can do that. It would be nice and make it a lot more user friendly in that case. 

As for the extra namespace, I'm down for whatever. I think as long as it's clear in the documentation, and it makes a nice beginner friendly UX, then it's worth it.

**Comment by paulcsmith** [comment]
Good point. In that case I think fully qualifying it and adding the `Api` namespace to the serialize might be good. People can leave off the `Api::Tacos` part once they understand how that works and want to do it

**Comment by paulcsmith** [comment]
Gonna go ahead and close this. Hopefully this bug in Crystal can be fixed so the error is correct. If you open the issue can you LMK? I might add a bounty to it because this is a pretty confusing error
