### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by repomaa** [luckyframework/lucky#770]
This is a just a suggestions but I thing it would be much cleaner and less error prone if all generated code would be namespaced _at least_ to the application name. Even more preferable in my opinion would be further namespacing by `Models`, `Pages`, `Actions` etc.

**Comment by jwoertink** [comment]
I just ran in to 2 issues where namespacing would have helped. Working on an app for building out a computer with specs, and I wanted a model named `System`. That's a module in Crystal, so you can't have a class named `System`. The other is an app where you can plan to go to fun things where a model would be named `Event`, but since that exists in crystal, you can't use that name. 

Generating apps with a default namespace could help to solve these issues, I think. I'm not sure about the secondary level of namespace, but at least a top level would help.

**Comment by paulcsmith** [comment]
This is a good point. It would also helps with class collisions because you'd always need to preface it with the namespace `render Pages::Users::Index`

I have a few concerns/questions with this approach:

1. What if you want to namespace by a domain. Would it be `Admin::Actions::Users::Index` or `Actions::Admin::Users::Index`? I'm guessing the later (start with `Actions`) but is that strange? This would definitely make it harder to use "concept" based file structure if we decide to go that way https://github.com/luckyframework/lucky/issues/642
2. It is a bit extra to type. Probably not a big deal, but worth addressing. 
3. I'm not sure how this would work with models because queries and forms inherit from the model. `class Queries::User < Models::User::BaseQuery` seems a bit strange :S

Any other thoughts/concerns with this approach? Any thoughts about this @edwardloveall?

**Comment by paulcsmith** [comment]
Actually it looks like we can define top-level classes from within a class 🤯

```crystal
class User
  class ::User::BaseQuery
  end
end

User::BaseQuery.new # Works
```

So we could still have `class Queries::User < User::BaseQuery` but this seems a bit too magical ⚡️. Thoughts?

**Comment by jwoertink** [comment]
I'm not particularly keen on the secondary level namespacing idea, though I can see how it could be helpful. What I was seeing was something more like:

```crystal
module MyBlogApp
  class Admin::Users::Index < BrowserAction
  end
end

module MyBlogApp
  class UserQuery < User::BaseQuery
  end
end
```

In my use case, I could then do

```crystal
module FunApp
  class Event < BaseModel
    table :events do
    end
  end
end
```

This makes `FunApp::Event` an Avram Model, and `::Event` a crystal core class.

**Comment by paulcsmith** [comment]
Ah I see. One issue I have with this is that it makes guides/tutorials strange because some people use `MyApp` some use their real app name, etc. Also some apps names are super long! If we did do app based namespacing, I'd suggest we default to `App`. The guides would be simple, it's short, etc.

**Comment by jwoertink** [comment]
I'd be ok with a simple `module App` as the parent namespace. It would make docs consistent, and no guess work for generating stuff.

**Comment by z64** [comment]
I'm wholly unfamiliar with Lucky's codebase, but I read this issue and it sounded similar to a problem I had, so thought I would bring it up:

I don't know what would be appropriate for Lucky, but when I ran into this I solved it by using a simple marker annotation to collect classes at compile time that are meant to integrate with the app.

```cr
module MyWebsite
  @[Lucky::App]
  class Blog
    # ..
  end
end
```

Anyway, just an idea 🙂

**Comment by jwoertink** [comment]
I still don't understand annotations much. What would this do exactly? With lucky, you'd have something like

```crystal
class Event < Avram::Model
end
```

but since you can't have a class named `Event` in the global scope, we would need to namespace it. Could we use annotations to solve that?

**Comment by repomaa** [comment]
Hm any concluding thoughts? `module App` as parent namespace? Would you be willing to accept a PR that would implement this for the generators?

**Comment by jwoertink** [comment]
I've actually started using very custom namespaces because I have to share models between apps. I have 2 different models both named `Site` which connect to different databases, so they are each namespaced. My thought is this is probably a case by case scenario. 

If we do decide to add this in, then I think default should be no namespace, and then some flag or maybe just the syntax itself.

```
lucky gen.model User                # generates just class User
lucky gen.model App::User      # generates class App::User
lucky gen.model User -n App  # maybe I don't like this afterall... but same App::User
```

But I'll defer to @paulcsmith on this one.
