### ISSUE TITLE
docs on many-to-many

### ISSUE THREAD

**Issue by KCErb** [luckyframework/lucky#773]
Hi there, thanks for the great library! :)

The docs did a great job of helping me put together a many-to-many relationship in my model, but I'm unsure with respect to migrations. The docs on migrations explain the `add_belongs_to` macro but I'm not sure where all that should go. 

For a start I should use it wherever a model has a `belongs_to` relationship, that makes sense. But what about the other side `has_many` and `has_one`?

If someone could give me a pointer, and if docs contributions are welcome, I'd be happy to put together a little write up to improve the missing points.

**Comment by paulcsmith** [comment]
I agree this could be better explained. Basically the the `add_belongs_to` goes in the migration for the table that the `belongs_to` in the model would go. I'm nt sure if that makes sense so I will share some examples. Maybe that would be best:

```crystal
class Employee 
  table :employees do
    has_one contact_info : ContactInfo
  end
end

class ContactInfo
  table :contact_info do
    belongs_to employee : Employee
  end
end

# migration for contact info
def migrate
  create :contact_info do
    # So this matches the `belongs_to` in the model almost exactly
    add_belongs_to employee : Employee, on_delete: :cascade
  end
end
```

And a many to many

```crystal
class Post 
  table :posts do
    has_many tags : Tag, through: :taggings
    has_many taggings : Tagging
  end
end

class Tag
  table :tags do
    has_many posts : Post, through: :taggings
    has_many taggings : Tagging
  end
end

class Tagging
  table :taggings do
    belongs_to post : Post
    belongs_to tag : Tag
  end
end

def migrate
  add_belongs_to post : Post, on_delete: :cascade
  add_belongs_to tag : Tag, on_delete: :cascade
end
```

Does that help? Any other points of confusion?

**Comment by KCErb** [comment]
Yes, that clears things up, I see now that it really just works through the join table, no magic. One of the two tables has a reference id, that's the `belongs_to` half. The other table has nothing, it's only the object that needs to know which table to look at, that's the `has_many` or `has_one` part of the deal.

Thanks for explaining.

I was wondering what each of the `on_delete` options does (`:cascade, :restrict, :nullify or :do_nothing`). I got some pointers by googling those words and finding Railsy explanations, but it'd be nice to have a quick note somewhere in the lucky docs too :)

**Comment by paulcsmith** [comment]
The Rails explanations match what Lucky does exactly because they rely on database constraints. So it relies on Postgres instead of anything Lucky/Rails specific. 

The truth is the Postgres docs are not easy to find or figure out so the Rails ones are probably better. But I'll try to describe what they do here just in case.

Let's say you have a `Comment` and `Post` model. `Comment` belongs_to`Post`.

So in your migration that adds comments you do

```
add_belongs_to post : Post
```

Now here's the problem. What if you have a comment that is related to Post with id `1` and we delete the Post with id `1`? If we did not have an `on_delete` constraint then the comment would just be sitting around in the database :(

Normally it is *very* easy to forget about this and you end up with lots of orphaned records. Lucky makes you think about it so you don't have orphaned records and bugs that come from having comments without posts :) 

The options to handle this are:

* `restrict` this say that is the parent (the `Post`) is deleted and there are any associated comments then the database should not allow the `Post` to be deleted
* `cascade` means that if the parent (`Post`) is deleted, to also delete the associated records (the comments)
* `nullify` means that if the `Post` is deleted that it should nullify the foreign key (basically disassociating it). This only works if the belongs_to is optional. Like if if you have a `Task` and it can belong to a `Project` or not. You may want to use `:nullify` so if the project is deleted, the task still exists, but is no longer associated with the project.
* `:do_nothing` - it does nothing :). I rarely use this because I almost always want one of those other options but it is there just in case.

Also worth noting `add_belongs_to` also automatically sets of a foreign key constraint. Lucky does a lot to help you keep your system running smoothly from the start, but could get better at explaining this :) I hope this helps

**Comment by jwoertink** [comment]
we now have docs for this https://www.luckyframework.org/guides/database/models#has-many-through-(many-to-many)
