### ISSUE TITLE
Using `JSON::Serializable` in tasks breaks on `Array(String)` field

### ISSUE THREAD

**Issue by lesderid** [luckyframework/lucky#776]
Using `JSON::Serializable` with `Array(String)` fields breaks with a compilation error in tasks.

Minimal example:

```crystal
require "json"

class Foo
  include JSON::Serializable

  property bar : Array(String)
end

class Db::LoadJson < LuckyCli::Task
  def summary; end

  def call
    foo = Foo.from_json(%({"bar": ["a", "b", "c"]}))
    pp foo
  end
end
```

Compiler log: https://pst.moe/paste/jorvlr

The same code on its own (i.e. outside of Lucky) works as expected (https://play.crystal-lang.org/#/r/6x1k).

Using `JSON.mapping` instead (as below) does work.

```crystal
require "json"
class Foo
  JSON.mapping(
    bar: Array(String),
  )
end

class Db::LoadJson < LuckyCli::Task
  def summary; end

  def call
    foo = Foo.from_json(%({"bar": ["a", "b", "c"]}))
    pp foo
  end
end
```

**Comment by jwoertink** [comment]
Ok, I've started digging in to this. I think it's a crystal issue, but I haven't narrowed down a smaller example yet. However, this works:

```crystal
require "json"

class Foo
  include JSON::Serializable

  property bar : String
end

class Db::LoadJson < LuckyCli::Task
  def summary; end

  def call
    foo = Foo.from_json(%({"bar": "a"}))
    pp foo
  end
end
```

It seems crystal is generating this `::Union(Array(String)).new(pull)` for the property `bar`, which throws a `wrong number of arguments for 'Array(String)#initialize' (given 1, expected 2, 0)` error.

If this is something that can be fixed in lucky, I'll send a PR, otherwise I'll try to submit an issue to crystal when I have some more info.

**Comment by jwoertink** [comment]
Found it! It's [wordsmith](https://github.com/luckyframework/wordsmith/blob/master/src/wordsmith/inflector/inflections.cr#L6) 😂  Now... *how* to fix that, I don't know, but @paulcsmith if you have an idea, or direction you can point me in....

**Comment by paulcsmith** [comment]
I think we could make it so it doesn’t inherit from Array and instead have an instance var called @array and then forward_missing_to @array

That may work. Nice sleuthing :)

**Comment by paulcsmith** [comment]
This seems to work now on Crystal 0.29 but either way I fixed the issue on Wordsmith (just in case it comes back in the future)
