### ISSUE TITLE
Pass in context to both CSRF methods

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky#836]
https://github.com/luckyframework/lucky/blob/master/src/lucky/tags/forgery_protection_helpers.cr should have the context passed in instead of using the instance var directly. See https://github.com/luckyframework/lucky/issues/831

**Comment by paulcsmith** [comment]
This will also require updates in Lucky CLI https://github.com/luckyframework/lucky_cli/blob/d249e2afbea6cfde69f9ccd6efeae1d620d7d2e4/src/browser_app_skeleton/src/components/shared/layout_head.cr#L11

**Comment by jwoertink** [comment]
Just notating here for anyone else that comes across this. We've decided to hold off for now because due to [these comments](https://github.com/luckyframework/lucky/pull/840#discussion_r300732776), it would introduce more issues than it's worth at the moment. 

The original idea behind this is just for clarity to remove a little "magic" where `@context` is used behind the scenes. 

We can revisit this at a later date though.

**Comment by jwoertink** [comment]
This actually isn't an issue anymore now that components automatically have access to `context` since https://github.com/luckyframework/lucky/pull/1488
