### ISSUE TITLE
route_not_found_handler_spec fails in CI

### ISSUE THREAD

**Issue by bdtomlin** [luckyframework/lucky#973]
```
Failures:
  1) Lucky::RouteNotFoundHandler has the fallback_action set from a fallback route
     Failure/Error: Lucky::RouteNotFoundHandler.fallback_action.should eq SampleFallbackAction::Index
       Expected: SampleFallbackAction::Index
            got: Rendering::FallbackRoute
     # spec/lucky/route_not_found_handler_spec.cr:24
  2) Lucky::RouteNotFoundHandler responds with a fallback action
     Failure/Error: output.to_s.should contain "Last chance"
       Expected:   "HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 18\r\n\r\nHey, you found me!"
       to include: "Last chance"
     # spec/lucky/route_not_found_handler_spec.cr:37
Finished in 12.58 seconds
424 examples, 2 failures, 0 errors, 0 pending
Failed examples:
crystal spec spec/lucky/route_not_found_handler_spec.cr:23 # Lucky::RouteNotFoundHandler has the fallback_action set from a fallback route
crystal spec spec/lucky/route_not_found_handler_spec.cr:27 # Lucky::RouteNotFoundHandler responds with a fallback action
The command "script/test" exited with 1.
```

There are two failing tests in CI. The fallback_route is a macro that is being set twice in two different tests [here](https://github.com/luckyframework/lucky/blob/8b52c573c2869cc434a0436fc71b9fecfa77f816/spec/lucky/fallback_action_spec.cr#L5-L9) and [here](https://github.com/luckyframework/lucky/blob/c8e9c1fe36617c324e5fc45e5b574311ed02af98/spec/lucky/route_not_found_handler_spec.cr#L5-L9).

I'm not sure why CI is different from running locally. I would think there would always be a failure depending on the order in which the fallbacks are compiled since fallback is a macro defined [here](https://github.com/luckyframework/lucky/blob/71dc544cca00675bdcd9451a13af35b4069482ad/src/lucky/routable.cr#L3-L6).

As you can see in the failed test, the fallback is set to Rendering::FallbackRoute which is again defined in the other test [here](https://github.com/luckyframework/lucky/blob/8b52c573c2869cc434a0436fc71b9fecfa77f816/spec/lucky/fallback_action_spec.cr#L5-L9).

Maybe the solution is to create `spec/support/sample_fallback_action.cr` and use it in both tests?

```crystal
# spec/support/sample_fallback_action.cr
class SampleFallbackAction::Index < TestAction
  fallback do
    plain_text "You found me"
  end
end
```

**Comment by jwoertink** [comment]
Yeah, I'm not sure why those specs fail on travis. The weird thing is we've had fallback routing for a while now, and these failing tests didn't start until like a month ago. 

We probably could roll with just a single example for that since those test cases are pretty simple. But I'm open to any other ideas if you have any. I've tried to get it to fail on both mac and linux as well as in docker locally, and it's fine in all those cases 🤷‍♂

**Comment by paulcsmith** [comment]
Another thing we've wanted to do that may  resolve this is switching to GitHub actions instead of Travis. Travis has been doing poorly ever since the acquisition so switching might be a good way to handle it! https://blog.roetzel.de/user/dave/post/using-github-actions-for-ci-of-lucky-apps

But also I think moving it to `spec/support` may be a good interim solution. Or maybe we could mark it as `private` e.g. Final solution if those don't work could be to name the classes differently :)

**Comment by bdtomlin** [comment]
I'll create a PR with the spec_support addition and see if it passes as I expect it will. I tried marking the classes as private which caused failures. I don't think changing the names of the classes would matter since they already have different names.
